- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create vprofile-vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cider_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout



